# Generated by Django 6.0.3 on 2026-04-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('property_interest', models.CharField(choices=[('residential', 'Residential Villas'), ('apartments', 'Luxury Apartments'), ('commercial', 'Commercial Space'), ('plot', 'Empty Plots')], default='residential', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
