# Generated by Django 6.0.3 on 2026-04-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_lead_preferred_location_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('room', 'Room / PG / Studio'), ('plot', 'Residential Plot'), ('villa', 'Independent Villa / House'), ('commercial', 'Commercial Space / Shop / Office'), ('building', 'Building / Complex'), ('farm', 'Farm House / Agricultural Land'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.property')),
            ],
        ),
    ]
